name: CI

on: pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: UziTech/action-setup-atom@v1.0.2
    - name: Install Hydrogen
      run: apm install
    - name: Test Hydrogen
      run: apm test
